FROM nvidia/cuda:12.9.0-cudnn-runtime-ubuntu24.04

RUN apt-get update && \
    apt-get install -y ffmpeg software-properties-common git && \
    add-apt-repository ppa:deadsnakes/ppa && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3.12 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:0.5.21 /uv /bin/uv
WORKDIR /root/deva_neuro

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project
COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen 
ENV WHISPER_DEVICE=cuda

CMD ["uv", "run", "-m", "deva_transcript"]