services:
  deva_transcript_cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./hugging_face_cache:/root/.cache/huggingface

  deva_transcript_gpu:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    volumes:
      - ./hugging_face_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]